In [ ]:
import os
import pandas as pd

# 定义目标文件夹路径
src_folder = "test2-ori"
des_folder = "test2"

# 初始化存储结果的列表
data = []

# 遍历 train 文件夹中的所有子文件夹和文件
for folder_name in os.listdir(src_folder):
    folder_path = os.path.join(src_folder, folder_name)
    if os.path.isdir(folder_path):  # 确保是文件夹
        for file_name in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file_name)
            if os.path.isfile(file_path):  # 确保是文件
                try:
                    data = pd.read_csv(file_path, encoding='gbk', header=None)
                    data = data.transpose()
                    data.columns = ['TIME', 'PRESSURE', 'CURRENT', 'DISPLACEMENT']
                    data = data[1:].reset_index(drop=True)
                    new_folder_path = os.path.join(des_folder, folder_name)
                    new_file_name = file_name.replace(".CSV", "-transpose.CSV")
                    new_file_path = os.path.join(new_folder_path, new_file_name)
                    data.to_csv(new_file_path, index=False, encoding='utf-8')
                except Exception as e:
                    print(f"无法读取文件 {file_path}: {e}")

   文件夹名             文件名  行数
0     N  焊接-曲线数据-26.CSV   4
1     N  焊接-曲线数据-32.CSV   4
2     N  焊接-曲线数据-33.CSV   4
3     N  焊接-曲线数据-27.CSV   4
4     N  焊接-曲线数据-31.CSV   4
..  ...             ...  ..
95    P  焊接-曲线数据-15.CSV   4
96    P  焊接-曲线数据-14.CSV   4
97    P  焊接-曲线数据-28.CSV   4
98    P  焊接-曲线数据-16.CSV   4
99    P  焊接-曲线数据-17.CSV   4

[100 rows x 3 columns]

In [60]:
data

          TIME PRESSURE CURRENT DISPLACEMENT
0        0.008  -2.3201 -0.0457       5.7106
1        0.016  -2.3201 -0.0457       5.7059
2        0.024  -2.3201 -0.0457       5.7012
3        0.032  -2.3201 -0.0372       5.7012
4         0.04  -2.2154 -0.0457       5.6965
...        ...      ...     ...          ...
15460  123.709  22.0833 -0.0287       44.124
15461  123.717  22.0833 -0.0287       44.124
15462  123.725  22.0833 -0.0287       44.124
15463  123.733  22.0833 -0.0287       44.124
15464  123.741  22.0833 -0.0287       44.124

[15465 rows x 4 columns]

0        时间（S）   压力（KN）  电流（KA）  位移（MM）
0        时间（S）   压力（KN）  电流（KA）  位移（MM）
1        0.008  -2.3201 -0.0457  5.7106
2        0.016  -2.3201 -0.0457  5.7059
3        0.024  -2.3201 -0.0457  5.7012
4        0.032  -2.3201 -0.0372  5.7012
...        ...      ...     ...     ...
15461  123.709  22.0833 -0.0287  44.124
15462  123.717  22.0833 -0.0287  44.124
15463  123.725  22.0833 -0.0287  44.124
15464  123.733  22.0833 -0.0287  44.124
15465  123.741  22.0833 -0.0287  44.124

[15466 rows x 4 columns]

In [5]:
df['行数'].max()

np.int64(15942)

In [16]:
df[df.文件夹名=='1P']['行数'].min()

np.int64(2488)